Repository StEx2022-23/sql2regex, pull requests merged in 2022-05, with the labels that each got.

#23 teststructure for equivalent statements
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/converter/MultiSqlRegex.java
  src/main/java/sqltoregex/converter/SqlRegex.java
  src/main/java/sqltoregex/property/PropertyManager.java
  src/main/java/sqltoregex/property/PropertyMapBuilder.java
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/MultiSqlRegexTest.java
  src/test/java/sqltoregex/SqlRegexTest.java
  src/test/java/sqltoregex/equivalentStatements/EquivalentStatementTest.java
  src/test/java/sqltoregex/equivalentStatements/SupportedStatementType.java
  src/test/java/sqltoregex/property/PropertyManagerTest.java
  src/test/resources/sqltoregex/equivalentStatements/SELECT
Labels: feauture

#27 Expressiondeparser
  src/main/java/sqltoregex/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/property/SettingsManager.java
  src/main/java/sqltoregex/property/SettingsMapBuilder.java
  src/main/java/sqltoregex/property/UserProperty.java
  src/main/java/sqltoregex/property/UserSettings.java
  src/main/java/sqltoregex/property/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGenerator.java
  src/main/java/sqltoregex/property/regexgenerator/synonymgenerator/SynonymGenerator.java
  src/main/resources/static/config/defaultProperties.xml
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/property/SettingsManagerTest.java
  src/test/java/sqltoregex/property/UserSettingsTest.java
Labels: enhancement

#34 refactored Settings
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/property/SettingsManager.java
  src/main/java/sqltoregex/property/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/RegExGenerator.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/SettingsNodeListIterator.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/java/sqltoregex/settings/UserSettings.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/StringSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
  src/main/resources/templates/assets/settingsform.html
  src/main/resources/templates/home.html
  src/test/java/sqltoregex/SqlToRegexControllerTest.java
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
  src/test/java/sqltoregex/settings/SettingsMapBuilderTest.java
  src/test/java/sqltoregex/settings/UserSettingsTest.java
  src/test/java/sqltoregex/settings/regexgenerator/OrderRotationTest.java
  src/test/java/sqltoregex/settings/regexgenerator/SpellingMistakeTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGeneratorTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/StringSynonymGeneratorTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGeneratorTest.java
Labels: enhancement

#35 Reg ex generator refactoring
  src/main/java/sqltoregex/controller/GraphPreProcessor.java
  src/main/java/sqltoregex/controller/InternationalizationController.java
  src/main/java/sqltoregex/controller/MyErrorController.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/settings/RegExGenerator.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/UserSettings.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
  src/main/resources/static/config/defaultProperties.xml
  src/main/resources/templates/assets/settingsform/form.html
  src/main/resources/templates/assets/settingsform/formElements.html
  src/main/resources/templates/home.html
  src/test/java/sqltoregex/TestMain.java
  src/test/java/sqltoregex/controller/GraphPreProcessorTest.java
  src/test/java/sqltoregex/controller/MyErrorControllerTest.java
  src/test/java/sqltoregex/controller/RestApiControllerTest.java
  src/test/java/sqltoregex/controller/SqlToRegexControllerTest.java
  src/test/java/sqltoregex/settings/SettingsMapBuilderTest.java
  src/test/java/sqltoregex/settings/UserSettingsTest.java
  src/test/java/sqltoregex/settings/regexgenerator/OrderRotationTest.java
  src/test/java/sqltoregex/settings/regexgenerator/SpellingMistakeTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGeneratorTest.java
Labels: bug, enhancement

#37 Code fixes from UML
  documentation/UML.mdj
  src/main/java/sqltoregex/controller/GraphPreProcessor.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/SettingsNodeListIterator.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/java/sqltoregex/settings/UserSettings.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_eng.properties
  src/main/resources/static/config/defaultProperties.xml
  src/main/resources/templates/assets/settingsform/form.html
  src/test/java/sqltoregex/controller/GraphPreProcessorTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
  src/test/java/sqltoregex/settings/SettingsMapBuilderTest.java
  src/test/java/sqltoregex/settings/UserSettingsTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGeneratorTest.java
Labels: enhancement

#36 implement selectdeparser and related deparser like groupby, limit, ...
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/GroupByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/LimitDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/java/sqltoregex/settings/regexgenerator/ExpressionRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/resources/static/config/defaultProperties.xml
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/GroupByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/LimitDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/OrderByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/StatementDeParserForRegExTest.java
  src/test/java/sqltoregex/equivalentStatements/EquivalentStatementTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
  src/test/java/sqltoregex/settings/SettingsMapBuilderTest.java
  src/test/java/sqltoregex/settings/regexgenerator/ExpressionRotationTest.java
Labels: enhancement, feauture

#38 User setting into settings manager
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/UserSettings.java
  src/test/java/sqltoregex/controller/GraphPreProcessorTest.java
  src/test/java/sqltoregex/controller/SqlToRegexControllerTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
  src/test/java/sqltoregex/settings/UserSettingsTest.java
Labels: enhancement

#39 finalize select deparser
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/controller/GraphPreProcessor.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/GroupByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/LimitDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_eng.properties
  src/main/resources/templates/assets/settingsform/form.html
  src/main/resources/templates/home.html
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/controller/GraphPreProcessorTest.java
  src/test/java/sqltoregex/controller/SqlToRegexControllerTest.java
  src/test/java/sqltoregex/deparser/GroupByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/LimitDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/OrderByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/StatementDeParserForRegExTest.java
  src/test/java/sqltoregex/equivalentStatements/EquivalentStatementTest.java
  src/test/java/sqltoregex/settings/SettingsFormTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
Labels: enhancement

#52 update current uml
  documentation/UML.mdj
Labels: enhancement

#40 Insertdeparser
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/GroupByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/java/sqltoregex/settings/regexgenerator/ExpressionRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/GroupByElementRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/resources/static/config/properties.xml
  src/test/java/sqltoregex/deparser/GroupByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/InsertDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/LimitDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/OrderByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/StatementDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/TestUtils.java
  src/test/java/sqltoregex/settings/regexgenerator/GroupByElementRotationTest.java
  src/test/java/sqltoregex/settings/regexgenerator/RegExGeneratorTest.java
Labels: enhancement

#55 fix issue #42
  src/main/java/sqltoregex/settings/UserSettings.java
Labels: bug

#56 implement UpdateDeParser
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/UpdateDeParserForRegEx.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/UpdateDeParserForRegExTest.java
Labels: enhancement

#59 Create table
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/resources/static/config/properties.xml
  src/test/java/sqltoregex/deparser/CreateTableTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
  src/test/java/sqltoregex/settings/SettingsMapBuilderTest.java
Labels: enhancement
