Repository StEx2022-23/sql2regex, pull requests merged in 2022-06, with the labels that each got.

#62 Settings refactoring
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/controller/GraphPreProcessor.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/GroupByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/LimitDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/UpdateDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsContainer.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsMapBuilder.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/java/sqltoregex/settings/UserSettings.java
  src/main/java/sqltoregex/settings/regexgenerator/GroupByElementRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/resources/application.properties
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_us.properties
  src/main/resources/static/config/properties.xml
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/assets/settingsform/form.html
  src/test/java/sqltoregex/deparser/CreateTableTest.java
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/GroupByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/InsertDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/LimitDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/OrderByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/SettingsContainerTest.java
  src/test/java/sqltoregex/deparser/StatementDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/TestUtils.java
  src/test/java/sqltoregex/deparser/UpdateDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/UserSettingsPreparer.java
  src/test/java/sqltoregex/settings/SettingsContainerBuilderTest.java
  src/test/java/sqltoregex/settings/SettingsFormTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
  src/test/java/sqltoregex/settings/UserSettingsTest.java
  src/test/java/sqltoregex/settings/regexgenerator/GroupByElementRotationTest.java
  src/test/java/sqltoregex/settings/regexgenerator/OrderRotationTest.java
  src/test/java/sqltoregex/settings/regexgenerator/RegExGeneratorTest.java
  src/test/java/sqltoregex/settings/regexgenerator/SpellingMistakeTest.java
Labels: enhancement

#69 Visualization2frontend
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_us.properties
  src/main/resources/static/js/js_utils.js
  src/main/resources/static/styles/site.css
  src/main/resources/static/styles/site.scss
  src/main/resources/templates/assets/jsscripts.html
  src/main/resources/templates/assets/settingsform/form.html
  src/main/resources/templates/visualization.html
Labels: enhancement, feauture

#70 reduce duplicated code in regexgenerators
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
Labels: coding style

#72 spelling mistakes in create table
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
Labels: bug

#75 Update dependencies
  pom.xml
Labels: dependencies

#78 message properties casesensitive fix
  src/main/resources/lang/messages_en_US.properties
Labels: bug

#79 73 datatype synonyms in create table
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsContainer.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/config/properties.xml
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/assets/settingsform/form.html
  src/test/java/sqltoregex/settings/SettingsFormTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
Labels: enhancement

#82 Settings refactor
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/DeleteDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/GroupByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/LimitDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/UpdateDeParserForRegEx.java
  src/main/java/sqltoregex/settings/regexgenerator/IRegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/StringSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
  src/test/java/sqltoregex/deparser/CreateTableTest.java
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/TestUtils.java
  src/test/java/sqltoregex/settings/regexgenerator/OrderRotationTest.java
  src/test/java/sqltoregex/settings/regexgenerator/RegExGeneratorTest.java
  src/test/java/sqltoregex/settings/regexgenerator/SpellingMistakeTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGeneratorTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/StringSynonymGeneratorTest.java
Labels: enhancement

#84 implement value order option
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsContainer.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/config/properties.xml
  src/test/java/sqltoregex/deparser/InsertDeParserForRegExTest.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
Labels: enhancement

#85 added booleanfield = true equivalent
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
Labels: enhancement

#90 Join to where implementation
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/visitor/SelectVisitorJoinToWhere.java
  src/main/java/sqltoregex/visitor/StatementVisitorJoinToWhere.java
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/SelectVisitorJoinToWhereTest.java
  src/test/java/sqltoregex/equivalentStatements/EquivalentStatementTest.java
Labels: bug, enhancement

#88 alias support and having clause bug fix
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
Labels: bug, enhancement

#91 87 andexpression operator as synonym + small frontend adjustment
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGenerator.java
  src/main/resources/static/config/properties.xml
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/home.html
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/settings/SettingsContainerTest.java
Labels: enhancement

#92 Cockiebanner+javadoc
  README.md
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/ResourceConfig.java
  src/main/java/sqltoregex/RestApiController.java
  src/main/java/sqltoregex/SqlToRegexApplication.java
  src/main/java/sqltoregex/controller/GraphPreProcessor.java
  src/main/java/sqltoregex/controller/InternationalizationController.java
  src/main/java/sqltoregex/controller/MyErrorController.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/settings/SettingsContainer.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsNodeListIterator.java
  src/main/java/sqltoregex/settings/UserSettings.java
  src/main/java/sqltoregex/settings/regexgenerator/IRegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/StringSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
  src/main/java/sqltoregex/visitor/StatementVisitorJoinToWhere.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/assets/cookieBanner.html
  src/main/resources/templates/assets/footer.html
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/SelectVisitorJoinToWhereTest.java
  src/test/java/sqltoregex/TestMain.java
  src/test/java/sqltoregex/deparser/CreateTableTest.java
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/equivalentStatements/EquivalentStatementTest.java
  src/test/java/sqltoregex/settings/regexgenerator/RegExGeneratorTest.java
  src/test/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGeneratorTest.java
Labels: enhancement, coding style

#94 small frontend improvements
  package.json
  pom.xml
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/js/js_utils.js
  src/main/resources/static/styles/site.css
  src/main/resources/static/styles/site.scss
  src/main/resources/templates/about.html
  src/main/resources/templates/examples.html
  src/main/resources/templates/home.html
  src/main/resources/templates/visualization.html
Labels: enhancement

#96 add api
  README.md
  src/main/java/sqltoregex/RestApiController.java
  src/main/java/sqltoregex/api/ApiConvertObject.java
  src/main/java/sqltoregex/api/RestApiController.java
  src/test/java/sqltoregex/TestMain.java
  src/test/java/sqltoregex/api/ApiConvertObjectTest.java
  src/test/java/sqltoregex/api/RestApiControllerTest.java
  src/test/java/sqltoregex/controller/RestApiControllerTest.java
Labels: enhancement

#95 add some more javadoc
  pom.xml
  src/main/java/sqltoregex/controller/GraphPreProcessor.java
  src/main/java/sqltoregex/controller/InternationalizationController.java
  src/main/java/sqltoregex/controller/MyErrorController.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/DeleteDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/GroupByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/LimitDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/UpdateDeParserForRegEx.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/DateAndTimeFormatSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/StringSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
Labels: coding style

#101 added Tests for the most grammar options
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/resources/static/config/properties.xml
  src/test/java/sqltoregex/deparser/CreateTableTest.java
Labels: enhancement

#98 quotationmarks support
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/resources/templates/assets/settingsform/form.html
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/GroupByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
  src/test/java/sqltoregex/settings/regexgenerator/OrderRotationTest.java
Labels: enhancement

#99 javadoc, some little improvements, drop table, create database
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/api/ApiConvertObject.java
  src/main/java/sqltoregex/api/RestApiController.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/CreateDatabaseDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/DropDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsContainer.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsManager.java
  src/main/java/sqltoregex/settings/SettingsNodeListIterator.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/java/sqltoregex/settings/SettingsType.java
  src/main/java/sqltoregex/settings/UserSettings.java
  src/main/java/sqltoregex/settings/regexgenerator/IRegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/settings/regexgenerator/RegExGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/SpellingMistake.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/StringSynonymGenerator.java
  src/main/java/sqltoregex/settings/regexgenerator/synonymgenerator/SynonymGenerator.java
  src/main/java/sqltoregex/settings/validations/AssertMethodAsTrue.java
  src/main/java/sqltoregex/settings/validations/AssertMethodAsTrueList.java
  src/main/java/sqltoregex/settings/validations/AssertMethodAsTrueValidator.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/js/js_utils.js
  src/main/resources/static/sitemap.xml
  src/main/resources/static/styles/site.css
  src/main/resources/static/styles/site.scss
  src/main/resources/templates/assets/settingsform/form.html
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/controller/SqlToRegexControllerTest.java
  src/test/java/sqltoregex/deparser/CreateDatabaseTest.java
  src/test/java/sqltoregex/deparser/DropDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/TestUtils.java
  src/test/java/sqltoregex/equivalentStatements/EquivalentStatementTest.java
  src/test/java/sqltoregex/settings/SettingsFormTest.java
Labels: enhancement, invalid, coding style

#102 hotfix - dateformats
  src/main/resources/templates/assets/settingsform/form.html
Labels: bug

#103 Primary key in column and constraint
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsForm.java
  src/main/java/sqltoregex/settings/SettingsType.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/visitor/StatementVisitorKeyPlacement.java
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/config/properties.xml
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/api/ApiConvertObjectTest.java
  src/test/java/sqltoregex/deparser/CreateTableTest.java
  src/test/java/sqltoregex/visitor/SelectVisitorJoinToWhereTest.java
  src/test/java/sqltoregex/visitor/StatementVisitorKeyPlacementTest.java
Labels: enhancement

#104 fix some small frontend bugs + hotfixes
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/main/java/sqltoregex/visitor/StatementVisitorKeyPlacement.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/config/properties.xml
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/assets/settingsform/form.html
  src/main/resources/templates/home.html
  src/test/java/sqltoregex/controller/GraphPreProcessorTest.java
  src/test/java/sqltoregex/visitor/StatementVisitorKeyPlacementTest.java
Labels: bug

#108 add docs to gitIgnore
  .gitignore
Labels: coding style

#109 conversion hint canvas
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/js/bootstrap.min.js
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/assets/settingsform/form.html
  src/main/resources/templates/home.html
Labels: enhancement

#110 added right quotation mark support
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/DeleteDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/DropDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/LimitDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/StatementDeParserForRegEx.java
  src/main/java/sqltoregex/settings/regexgenerator/OrderRotation.java
  src/test/java/sqltoregex/deparser/CreateTableTest.java
  src/test/java/sqltoregex/deparser/DeleteDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/DropDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/GroupByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/InsertDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/LimitDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/OrderByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/SelectDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/StatementDeParserForRegExTest.java
  src/test/java/sqltoregex/settings/regexgenerator/OrderRotationTest.java
Labels: bug, enhancement

#114 some fixes in SelectDeParser (aggreatefunction, fully qualified names, having clause, order by clause, ...) , quotationmark behaviour in InsertDeParser incl. SpellingMistake, new Setting for StringValueSpellingMistake, add some synonyms
  src/main/java/sqltoregex/ConverterManagement.java
  src/main/java/sqltoregex/controller/SqlToRegexController.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/InsertDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/OrderByDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/SelectDeParserForRegEx.java
  src/main/java/sqltoregex/settings/SettingsContainer.java
  src/main/java/sqltoregex/settings/SettingsOption.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/config/properties.xml
  src/test/java/sqltoregex/controller/GraphPreProcessorTest.java
  src/test/java/sqltoregex/deparser/OrderByDeParserForRegExTest.java
  src/test/java/sqltoregex/deparser/TestUtils.java
  src/test/java/sqltoregex/settings/SettingsManagerTest.java
Labels: bug

#112 uses expressions in UpdateDeParser, fix escaping in ExpressionDeParser, fix visualization-button-bug, fix datetime-replacing, fix column definition behaviour
  src/main/java/sqltoregex/deparser/CreateTableDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/java/sqltoregex/deparser/UpdateDeParserForRegEx.java
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/assets/settingsform/form.html
  src/test/java/sqltoregex/deparser/UpdateDeParserForRegExTest.java
Labels: bug

#118 fix some issues
  src/main/java/sqltoregex/deparser/ExpressionDeParserForRegEx.java
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/js/js_utils.js
  src/main/resources/templates/assets/settingsform/form.html
  src/main/resources/templates/home.html
  src/test/java/sqltoregex/deparser/ExpressionDeParserForRegExTest.java
Labels: bug, enhancement

#120 add report bug button, refactor html files to using templates
  src/main/resources/lang/messages_de.properties
  src/main/resources/lang/messages_en_US.properties
  src/main/resources/static/js/js_utils.js
  src/main/resources/static/styles/site.css
  src/main/resources/static/styles/site.scss
  src/main/resources/templates/about.html
  src/main/resources/templates/assets/alertTemplate.html
  src/main/resources/templates/assets/footer.html
  src/main/resources/templates/assets/offcanvasElement.html
  src/main/resources/templates/assets/reportbug.html
  src/main/resources/templates/assets/researchGoalTemplate.html
  src/main/resources/templates/assets/timelineItemTemplate.html
  src/main/resources/templates/assets/toastTemplate.html
  src/main/resources/templates/home.html
Labels: enhancement

#121 Update issue templates
  .github/ISSUE_TEMPLATE/report-a-bug.md
Labels: enhancement

#143 fix #142
  src/main/java/sqltoregex/visitor/StatementVisitorJoinToWhere.java
  src/test/java/sqltoregex/ConverterManagementTest.java
  src/test/java/sqltoregex/visitor/SelectVisitorJoinToWhereTest.java
Labels: bug
